name: WebGoat CI/CD Pipeline

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    name: Build and Test WebGoat
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Java environment
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17' # Use the appropriate Java version for WebGoat
          distribution: 'temurin'

      # Step 3: Cache Maven dependencies
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Step 4: Build the project
      - name: Build with Maven
        run: mvn clean install -DskipTests=true

      # Step 5: Run tests
      - name: Run Tests
        run: mvn test

      # Step 6: Upload test results (optional)
      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: target/surefire-reports/

  deploy:
    name: Deploy WebGoat
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy to Server
        run: echo "Add deployment steps here"
